- name: Configure clickhouse
  become: true
  template:
    src: config.xml
    dest: "{{ clickhouse_config_file }}"

- name: Retart clickhouse server
  become: true
  service:
    name: clickhouse-server
    state: restarted
