- name: Install the latest clickhouse for Debian
  import_tasks: debian.yml

- name: Setup clickhouse cluster
  import_tasks: config.yml

- name: Create metadata
  import_tasks: metadata.yml

- name: Import data
  import_tasks: data.yml