- name: Copy SQL file
  copy:
    src: "tutorial.sql"
    dest: "{{ work_dir }}/"

- name: Create tutorial database
  shell: "cat tutorial.sql | clickhouse-client -mn"
  args:
    chdir: "{{ work_dir }}"