- name: Copy SQL file
  copy:
    src: "tutorial.sql"
    dest: "{{ ansible_env.HOME }}/clickhouse-workdir/"

- name: Create tutorial database
  shell: "cat tutorial.sql | clickhouse-client -mn"
  args:
    chdir: "{{ ansible_env.HOME }}/clickhouse-workdir"