## HTTP configuration
http:
  routers:
    to-awx:
      entryPoints:
        - "web"
        - "websecure"
      rule: "PathPrefix(`/`)"
      service: awx-service

  services:
    awx-service:
      loadBalancer:
        servers:
          - url: "http://{{ awx_ip }}:{{ awx_port }}/"