## HTTP configuration
http:
  routers:
    to-awx:
      service: awx-service
      rule: "PathPrefix(`/`)"
  services:
    awx-service:
      loadBalancer:
        servers:
          - url: "http://{{ awx_ip }}:{{ awx_port }}/"