## HTTP configuration
http:
  routers:
    to-awx:
      entryPoints:
        - "web"
      rule: "Host(`awx`)"
      service: awx-service

    to-vault:
      entryPoints:
        - "web"
      rule: "Host(`vault`)"
      service: vault-service

    dashboard:
      entryPoints:
        - "web"
      rule: "Host(`mi`) && PathPrefix(`/`)"
      service: dashboard@internal

    api:
      entryPoints:
        - "web"
      rule: "Host(`mi`) && PathPrefix(`/api`)"
      service: api@internal

  services:
    awx-service:
      loadBalancer:
        servers:
          - url: "http://{{ awx_ip }}:{{ awx_port }}/"

    vault-service:
      loadBalancer:
        servers:
          - url: "https://{{ vault_ip }}:{{ vault_port }}/"
