## HTTP configuration
http:
  routers:
    to-openshift:
      entryPoints:
        - "web"
        - "websecure"
      rule: "PathPrefix(`/`)"
      service: openshift-service
  serversTransports:
    local-transport:
      insecureSkipVerify: true
  services:
    openshift-service:
      loadBalancer:
        servers:
          - url: "http://{{ awx_ip }}:{{ awx_port }}/"