# specific entry points
entryPoints:
  web:
    address: ":80"
#  websecure:
#    address: ":443"
# File configuration backend
providers:
  file:
    filename: "{{ traefik_dir }}/routing.yml"
  docker:
    endpoint: "unix:///var/run/docker.sock"

serversTransport:
  insecureSkipVerify: true

# this is not used for local network
certificatesResolvers:
  cert-resolver:
    acme:
      caServer: https://acme-staging-v02.api.letsencrypt.org/directory
      email: w.yunbo@gmail.com
      storage: "{{ traefik_dir }}/acme.json"
      httpChallenge:
        # used during the challenge
        entryPoint: web

# API and dashboard configuration
api:
  insecure: true

accessLog:
  filePath: "{{ traefik_dir }}/access.log"

log:
  filePath: "{{ traefik_dir }}/traefik.log"