- name: Create traefik directory
  ansible.builtin.file:
    path: "{{ traefik_dir }}"
    state: directory
    mode: "0755"

- name: Install the traefik binary
  ansible.builtin.unarchive:
    src: "https://github.com/traefik/traefik/releases/download/{{ traefik_version }}/traefik_{{ traefik_version }}_linux_amd64.tar.gz"
    creates: "{{ traefik_dir }}/traefik"
    dest: "{{ traefik_dir }}/"
    mode: "u+rx"
    remote_src: yes

- name: Setup traefik
  ansible.builtin.template:
    src: "{{ item }}"
    dest: "{{ traefik_dir }}/"
  loop:
    - traefik.yml
    - routing.yml

- name: Install traefik as sytemd unit
  ansible.builtin.template:
    src: "traefik.service"
    dest: "/etc/systemd/system/"
  become: yes

- name: Restart traefik and enable it as service
  ansible.builtin.systemd:
    state: restarted
    daemon_reload: yes
    enabled: yes
    name: traefik
  become: yes