## HTTP configuration
http:
  routers:
    to-awx:
      service: awx-service
      rule: "Path(`/awx/`)"

  services:
    awx-service:
      loadBalancer:
        servers:
          - url: "http://192.168.49.2:31828/"